Fix AttributeError due to name change
File "/Users/gavinkyte/OneDrive/makerspace/shift_scheduler/scheduler.py", line 83, in convert_availability_to_slots
    times_by_day = self.get_times_of_day_for_whole_cycle(avail)
AttributeError: 'ScheduleInterpreter' object has no attribute 'get_times_of_day_for_whole_cycle'