Fix TypeError in assign_shifts
File "/Users/gavinkyte/OneDrive/makerspace/shift_scheduler/matcher.py", line 38, in assign_shifts
    vertex_2_slot = dict(vertices, slots)
TypeError: dict expected at most 1 arguments, got 2

Needed to use zip inside dict()