Fix TypeError from decoding issue in decide_matching
File "/Users/gavinkyte/OneDrive/makerspace/shift_scheduler/matcher.py", line 51, in decide_matching
    solver_output = (check_output(solver_args)).split("\n")
TypeError: a bytes-like object is required, not 'str'